/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WhyRouteImport } from './routes/why'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBookRouteImport } from './routes/dashboard/book'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard/favorites'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardJourneyRouteImport } from './routes/dashboard/journey'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardPaymentRouteImport } from './routes/dashboard/payment'
import { Route as DashboardPaymentSuccessRouteImport } from './routes/dashboard/payment-success'
import { Route as DashboardPlatformRouteImport } from './routes/dashboard/platform'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardQrRouteImport } from './routes/dashboard/qr'
import { Route as DashboardRefundSuccessRouteImport } from './routes/dashboard/refund-success'
import { Route as DashboardRefundsRouteImport } from './routes/dashboard/refunds'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTicketRouteImport } from './routes/dashboard/ticket'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard/tickets'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DashboardWalletRechargeSuccessRouteImport } from './routes/dashboard/wallet-recharge-success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookRoute = DashboardBookRouteImport.update({
  id: '/dashboard/book',
  path: '/dashboard/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJourneyRoute = DashboardJourneyRouteImport.update({
  id: '/dashboard/journey',
  path: '/dashboard/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentRoute = DashboardPaymentRouteImport.update({
  id: '/dashboard/payment',
  path: '/dashboard/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentSuccessRoute = DashboardPaymentSuccessRouteImport.update({
  id: '/dashboard/payment-success',
  path: '/dashboard/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlatformRoute = DashboardPlatformRouteImport.update({
  id: '/dashboard/platform',
  path: '/dashboard/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/dashboard/qr',
  path: '/dashboard/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRefundSuccessRoute = DashboardRefundSuccessRouteImport.update({
  id: '/dashboard/refund-success',
  path: '/dashboard/refund-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRefundsRoute = DashboardRefundsRouteImport.update({
  id: '/dashboard/refunds',
  path: '/dashboard/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketRoute = DashboardTicketRouteImport.update({
  id: '/dashboard/ticket',
  path: '/dashboard/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/dashboard/tickets',
  path: '/dashboard/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRechargeSuccessRoute =
  DashboardWalletRechargeSuccessRouteImport.update({
    id: '/dashboard/wallet-recharge-success',
    path: '/dashboard/wallet-recharge-success',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/why': typeof WhyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/payment-success': typeof DashboardPaymentSuccessRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/refund-success': typeof DashboardRefundSuccessRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/ticket': typeof DashboardTicketRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wallet-recharge-success': typeof DashboardWalletRechargeSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/why': typeof WhyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/payment-success': typeof DashboardPaymentSuccessRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/refund-success': typeof DashboardRefundSuccessRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/ticket': typeof DashboardTicketRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wallet-recharge-success': typeof DashboardWalletRechargeSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/why': typeof WhyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/payment-success': typeof DashboardPaymentSuccessRoute
  '/dashboard/platform': typeof DashboardPlatformRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/refund-success': typeof DashboardRefundSuccessRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/ticket': typeof DashboardTicketRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/wallet-recharge-success': typeof DashboardWalletRechargeSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/network'
    | '/register'
    | '/why'
    | '/dashboard/book'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/journey'
    | '/dashboard/notifications'
    | '/dashboard/payment'
    | '/dashboard/payment-success'
    | '/dashboard/platform'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/refund-success'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/ticket'
    | '/dashboard/tickets'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/dashboard/wallet-recharge-success'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/network'
    | '/register'
    | '/why'
    | '/dashboard/book'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/journey'
    | '/dashboard/notifications'
    | '/dashboard/payment'
    | '/dashboard/payment-success'
    | '/dashboard/platform'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/refund-success'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/ticket'
    | '/dashboard/tickets'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/dashboard/wallet-recharge-success'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/network'
    | '/register'
    | '/why'
    | '/dashboard/book'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/journey'
    | '/dashboard/notifications'
    | '/dashboard/payment'
    | '/dashboard/payment-success'
    | '/dashboard/platform'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/refund-success'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/ticket'
    | '/dashboard/tickets'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/dashboard/wallet-recharge-success'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  RegisterRoute: typeof RegisterRoute
  WhyRoute: typeof WhyRoute
  DashboardBookRoute: typeof DashboardBookRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardJourneyRoute: typeof DashboardJourneyRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentRoute: typeof DashboardPaymentRoute
  DashboardPaymentSuccessRoute: typeof DashboardPaymentSuccessRoute
  DashboardPlatformRoute: typeof DashboardPlatformRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardRefundSuccessRoute: typeof DashboardRefundSuccessRoute
  DashboardRefundsRoute: typeof DashboardRefundsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTicketRoute: typeof DashboardTicketRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWalletRechargeSuccessRoute: typeof DashboardWalletRechargeSuccessRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/book': {
      id: '/dashboard/book'
      path: '/dashboard/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/journey': {
      id: '/dashboard/journey'
      path: '/dashboard/journey'
      fullPath: '/dashboard/journey'
      preLoaderRoute: typeof DashboardJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payment': {
      id: '/dashboard/payment'
      path: '/dashboard/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payment-success': {
      id: '/dashboard/payment-success'
      path: '/dashboard/payment-success'
      fullPath: '/dashboard/payment-success'
      preLoaderRoute: typeof DashboardPaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/platform': {
      id: '/dashboard/platform'
      path: '/dashboard/platform'
      fullPath: '/dashboard/platform'
      preLoaderRoute: typeof DashboardPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/dashboard/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/refund-success': {
      id: '/dashboard/refund-success'
      path: '/dashboard/refund-success'
      fullPath: '/dashboard/refund-success'
      preLoaderRoute: typeof DashboardRefundSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/refunds': {
      id: '/dashboard/refunds'
      path: '/dashboard/refunds'
      fullPath: '/dashboard/refunds'
      preLoaderRoute: typeof DashboardRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ticket': {
      id: '/dashboard/ticket'
      path: '/dashboard/ticket'
      fullPath: '/dashboard/ticket'
      preLoaderRoute: typeof DashboardTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet-recharge-success': {
      id: '/dashboard/wallet-recharge-success'
      path: '/dashboard/wallet-recharge-success'
      fullPath: '/dashboard/wallet-recharge-success'
      preLoaderRoute: typeof DashboardWalletRechargeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  RegisterRoute: RegisterRoute,
  WhyRoute: WhyRoute,
  DashboardBookRoute: DashboardBookRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardJourneyRoute: DashboardJourneyRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentRoute: DashboardPaymentRoute,
  DashboardPaymentSuccessRoute: DashboardPaymentSuccessRoute,
  DashboardPlatformRoute: DashboardPlatformRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardRefundSuccessRoute: DashboardRefundSuccessRoute,
  DashboardRefundsRoute: DashboardRefundsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTicketRoute: DashboardTicketRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWalletRechargeSuccessRoute: DashboardWalletRechargeSuccessRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
