import jsPDF from "jspdf";
import { CATEGORY_LABEL, type Ticket } from "./tickets";
import { pushNotification } from "./notifications";
import { toast } from "sonner";

export function downloadTicketPdf(t: Ticket) {
  const doc = new jsPDF({ unit: "pt", format: "a5" });
  const w = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(232, 71, 14);
  doc.rect(0, 0, w, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("RailConnect", 24, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Digital Railway Ticket", 24, 50);
  doc.setFontSize(11);
  doc.text(`PNR ${t.pnr}`, w - 24, 32, { align: "right" });
  doc.text(t.type.toUpperCase(), w - 24, 50, { align: "right" });

  // Body
  doc.setTextColor(20, 20, 20);
  let y = 110;
  const row = (k: string, v: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(k, 24, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(20, 20, 20);
    doc.text(v, w - 24, y, { align: "right" });
    y += 24;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const route = `${t.from}${t.fromCode ? ` (${t.fromCode})` : ""}  →  ${t.to}${t.toCode ? ` (${t.toCode})` : ""}`;
  doc.text(route, 24, y);
  y += 28;

  row("Ticket ID", t.id.slice(0, 8).toUpperCase());
  row("PNR", t.pnr);
  if (t.txnId) row("Transaction ID", t.txnId);
  row("Issued", new Date(t.createdAt).toLocaleString());
  row("Valid until", new Date(t.validUntil).toLocaleString());
  row("Passengers", `${t.adults} adult · ${t.children} child`);
  row("Train category", t.category ? CATEGORY_LABEL[t.category] : "Passenger");
  row("Railway zone", t.line);
  if (t.paymentMethod) row("Payment method", t.paymentMethod);
  row("Amount paid", `INR ${t.fare}`);
  row("Status", t.status.toUpperCase());

  // QR block
  y += 8;
  const qrSize = 96;
  const qrX = (w - qrSize) / 2;
  drawPseudoQr(doc, t.pnr, qrX, y, qrSize);
  y += qrSize + 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("Scan at the gate to board", w / 2, y, { align: "center" });
  y += 14;

  // Footer note
  y += 12;
  doc.setDrawColor(232, 71, 14);
  doc.setLineWidth(1);
  doc.line(24, y, w - 24, y);
  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by RailConnect · Carry a valid photo ID. Produce this ticket on demand.",
    24,
    y,
  );

  doc.save(`railconnect-${t.pnr}.pdf`);
}

export function downloadTicketAndNotify(t: Ticket, userId?: string) {
  try {
    downloadTicketPdf(t);
    toast.success("Ticket PDF downloaded", {
      description: `railconnect-${t.pnr}.pdf saved to your device.`,
    });
    if (userId) {
      pushNotification(userId, {
        category: "booking",
        severity: "success",
        title: "Ticket PDF downloaded",
        body: `${t.from} → ${t.to} · PNR ${t.pnr}`,
        href: "/dashboard/tickets",
      });
    }
  } catch (e) {
    toast.error("Could not generate PDF", {
      description: "Please try again in a moment.",
    });
  }
}

function drawPseudoQr(doc: jsPDF, seed: string, x: number, y: number, size: number) {
  const grid = 21;
  const cell = size / grid;
  // background
  doc.setFillColor(255, 255, 255);
  doc.rect(x - 4, y - 4, size + 8, size + 8, "F");
  doc.setDrawColor(232, 71, 14);
  doc.setLineWidth(0.8);
  doc.rect(x - 4, y - 4, size + 8, size + 8);

  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;

  doc.setFillColor(20, 20, 20);
  for (let gy = 0; gy < grid; gy++) {
    for (let gx = 0; gx < grid; gx++) {
      const finder = (gx < 7 && gy < 7) || (gx >= grid - 7 && gy < 7) || (gx < 7 && gy >= grid - 7);
      if (finder) continue;
      h = (h * 1103515245 + 12345) >>> 0;
      if ((h & 1) === 1) {
        doc.rect(x + gx * cell, y + gy * cell, cell, cell, "F");
      }
    }
  }

  // finders
  const corners: [number, number][] = [
    [0, 0],
    [grid - 7, 0],
    [0, grid - 7],
  ];
  for (const [fx, fy] of corners) {
    doc.setFillColor(232, 71, 14);
    doc.rect(x + fx * cell, y + fy * cell, 7 * cell, 7 * cell, "F");
    doc.setFillColor(255, 255, 255);
    doc.rect(x + (fx + 1) * cell, y + (fy + 1) * cell, 5 * cell, 5 * cell, "F");
    doc.setFillColor(20, 20, 20);
    doc.rect(x + (fx + 2) * cell, y + (fy + 2) * cell, 3 * cell, 3 * cell, "F");
  }
}
